//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LayoutTool.Models.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LayoutTool.Models.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;abTests&quot;:
        ///	[
        ///		{
        ///			&quot;ID&quot;:&quot;9&quot;,
        ///			&quot;Name&quot;:&quot;Test name as string&quot;,
        ///			&quot;Description&quot;:&quot;Long description of the test&quot;,
        ///			&quot;testCasesSets&quot;:[
        ///				{
        ///					&quot;brand&quot;:&quot;1&quot;,
        ///					&quot;skin&quot;:&quot;4&quot;,
        ///					&quot;lang&quot;:&quot;en&quot;,
        ///					&quot;testCases&quot;:[
        ///						{
        ///							&quot;ID&quot;:&quot;1&quot;, &quot;isDefault&quot;:&quot;true&quot;, &quot;Method&quot;:&quot;1&quot;, &quot;Name&quot;:&quot;FLASH&quot;, &quot;UsePercentage&quot;:&quot;99&quot;, &quot;Description&quot;:&quot;MLNG is an FLASH game&quot;,
        ///							&quot;ClientFolder&quot;:&quot;&quot;,
        ///							&quot;configurationPaths&quot;:{
        ///										&quot;navigationPlanPath&quot;: &quot;Configuration/navigation_plans/brand_0/skin_4/navigatio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ABTestConfig {
            get {
                return ResourceManager.GetString("ABTestConfig", resourceCulture);
            }
        }
    }
}
