using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace GGPMockBootstrapper.Models
{
    public partial class BrandInfo
    {
        public static readonly BrandInfo[] AllBrands = new BrandInfo[]
        {
            new BrandInfo(0, "888casino", "8canew", 4),
            new BrandInfo(1, "888poker", "8po", 4),
            new BrandInfo(2, "Reef Club Casino", "RCC", 4),
            new BrandInfo(4, "RileysPoker", "RLP", 4),
            new BrandInfo(5, "Tower Torneos", "TTP", 4),
            new BrandInfo(6, "LuckyAceCasino.com", "LAC", 4),
            new BrandInfo(7, "LuckyAcePoker.com", "LAP", 4),
            new BrandInfo(8, "888sport", "SB", 4),
            new BrandInfo(10, "Goldchip", "GC", 4),
            new BrandInfo(11, "LittleWoods", "LW", 4),
            new BrandInfo(12, "888", "8UO", 4),
            new BrandInfo(13, "LexGaming", "LEX", 4),
            new BrandInfo(14, "RacingPostGaming", "RacingPost", 4),
            new BrandInfo(15, "apostenoseutime.com", "AP", 4),
            new BrandInfo(16, "SuproCasino.com", "Sup", 4),
            new BrandInfo(17, "Play848", "848", 4),
            new BrandInfo(19, "Linden Lab", "LL", 4),
            new BrandInfo(20, "WSOP Online", "WSP", 4),
            new BrandInfo(21, "WSOP Casino", "CWP", 4),
            new BrandInfo(22, "bwin.it", "BIT", 1),
            new BrandInfo(23, "GD Vegas", "GDV", 1),
            new BrandInfo(24, "EuroCity", "ECC", 4),
            new BrandInfo(25, "WSOP-USA", "WSU", 4),
            new BrandInfo(26, "Free People's Casino", "FPC", 4),
            new BrandInfo(27, "888Pachinko", "Pac", 4),
            new BrandInfo(28, "888.fr", "PFR", 5),
            new BrandInfo(31, "888.it", "8IT", 1),
            new BrandInfo(32, "SPINWIN", "SPW", 4),
            new BrandInfo(33, "People's", "PEO", 1),
            new BrandInfo(34, "NEW Casino-on-Net", "NCO", 4),
            new BrandInfo(35, "bbet", "bbt", 1),
            new BrandInfo(36, "LotosPlay", "LTS", 4),
            new BrandInfo(37, "BetItaly", "BTI", 1),
            new BrandInfo(38, "betpointplus", "BPP", 1),
            new BrandInfo(39, "Betshopitalia", "BSI", 1),
            new BrandInfo(40, "Casinò di SanRemo", "CSR", 1),
            new BrandInfo(41, "EventoGioco", "ETG", 1),
            new BrandInfo(42, "FiveBet", "FVB", 1),
            new BrandInfo(43, "HitStars", "HST", 1),
            new BrandInfo(44, "gamelux", "gam", 1),
            new BrandInfo(45, "Poker-Bet", "PKB", 1),
            new BrandInfo(46, "puntoscommesse", "PTS", 1),
            new BrandInfo(47, "replatz", "RPZ", 1),
            new BrandInfo(48, "ScommesseItalia", "SCI", 1),
            new BrandInfo(49, "Scommettendo", "SCT", 1),
            new BrandInfo(50, "SkillBet", "SKB", 1),
            new BrandInfo(51, "VinciTuBet", "VCT", 1),
            new BrandInfo(52, "QuiGioco", "QuG", 1),
            new BrandInfo(53, "iGameLab", "iGL", 1),
            new BrandInfo(54, "giocopiu", "Gio", 1),
            new BrandInfo(55, "pianetascommesse", "tiv", 1),
            new BrandInfo(56, "omnibet", "Omn", 1),
            new BrandInfo(57, "King.com", "Kng", 1),
            new BrandInfo(58, "888.es", "8ES", 2),
            new BrandInfo(59, "Snoqualmie", "Snq", 4),
            new BrandInfo(60, "WSOP.com NV", "WSN", 3),
            new BrandInfo(61, "TIpoker USA", "TiP", 4),
            new BrandInfo(62, "888poker NV Free", "8NV", 4),
            new BrandInfo(63, "MAGIC888 casino", "8CC", 4),
            new BrandInfo(64, "TIpoker NV", "INV", 3),
            new BrandInfo(65, "TrumpPoker NV", "TNV", 3),
            new BrandInfo(66, "888poker NV", "PNV", 3),
            new BrandInfo(67, "SnapCall", "SNC", 4),
            new BrandInfo(68, "HarringtonGamingOnline.com", "Hri", 6),
            new BrandInfo(69, "Dover Downs Hotel and Casino", "Dod", 6),
            new BrandInfo(70, "Delawarepark.com", "DEP", 6),
            new BrandInfo(71, "WSOP.com-NJ", "CNJ", 7),
            new BrandInfo(72, "Harrah's Casino", "HNJ", 7),
            new BrandInfo(73, "888.com NJ", "8NJ", 7),
            new BrandInfo(74, "Wynn Interactive", "WNJ", 7),
            new BrandInfo(75, "888.dk", "8DK", 8),
            new BrandInfo(76, "888.ro", "8ro", 9),
            new BrandInfo(77, "888.be", "8be", 10),
            new BrandInfo(79, "888.pt", "8pt", 14),
            new BrandInfo(80, "888poker.net", "8nt", 4)
        };
    }
}
