//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesPortal.Client.Models.GamesPortalHubContracts {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GameSynchronizationFinishedData", Namespace="http://schemas.datacontract.org/2004/07/GamesPortal.Service.SignalR")]
    [System.SerializableAttribute()]
    public partial class GameSynchronizationFinishedData : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private GamesPortal.Client.Models.GamesPortalHubContracts.RecordChangeType ChangeTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid GameIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsExternalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GamesPortal.Client.Models.GamesPortalHubContracts.RecordChangeType ChangeType {
            get {
                return this.ChangeTypeField;
            }
            set {
                this.ChangeTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid GameId {
            get {
                return this.GameIdField;
            }
            set {
                this.GameIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsExternal {
            get {
                return this.IsExternalField;
            }
            set {
                this.IsExternalField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RecordChangeType", Namespace="http://schemas.datacontract.org/2004/07/GamesPortal.Service")]
    public enum RecordChangeType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Added = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Changed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FullGamesSynchronizationFinishedData", Namespace="http://schemas.datacontract.org/2004/07/GamesPortal.Service.SignalR")]
    [System.SerializableAttribute()]
    public partial class FullGamesSynchronizationFinishedData : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SynchronizationTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SynchronizedByField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SynchronizationTime {
            get {
                return this.SynchronizationTimeField;
            }
            set {
                this.SynchronizationTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SynchronizedBy {
            get {
                return this.SynchronizedByField;
            }
            set {
                this.SynchronizedByField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GamesPortalHubContracts.IGamesPortalHubContext")]
    public interface IGamesPortalHubContext {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamesPortalHubContext/GameSynchronizationFinished", ReplyAction="http://tempuri.org/IGamesPortalHubContext/GameSynchronizationFinishedResponse")]
        void GameSynchronizationFinished(GamesPortal.Client.Models.GamesPortalHubContracts.GameSynchronizationFinishedData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamesPortalHubContext/GameSynchronizationFinished", ReplyAction="http://tempuri.org/IGamesPortalHubContext/GameSynchronizationFinishedResponse")]
        System.Threading.Tasks.Task GameSynchronizationFinishedAsync(GamesPortal.Client.Models.GamesPortalHubContracts.GameSynchronizationFinishedData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamesPortalHubContext/FullGamesSynchronizationFinished", ReplyAction="http://tempuri.org/IGamesPortalHubContext/FullGamesSynchronizationFinishedRespons" +
            "e")]
        void FullGamesSynchronizationFinished(GamesPortal.Client.Models.GamesPortalHubContracts.FullGamesSynchronizationFinishedData data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGamesPortalHubContext/FullGamesSynchronizationFinished", ReplyAction="http://tempuri.org/IGamesPortalHubContext/FullGamesSynchronizationFinishedRespons" +
            "e")]
        System.Threading.Tasks.Task FullGamesSynchronizationFinishedAsync(GamesPortal.Client.Models.GamesPortalHubContracts.FullGamesSynchronizationFinishedData data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGamesPortalHubContextChannel : GamesPortal.Client.Models.GamesPortalHubContracts.IGamesPortalHubContext, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GamesPortalHubContextClient : System.ServiceModel.ClientBase<GamesPortal.Client.Models.GamesPortalHubContracts.IGamesPortalHubContext>, GamesPortal.Client.Models.GamesPortalHubContracts.IGamesPortalHubContext {
        
        public GamesPortalHubContextClient() {
        }
        
        public GamesPortalHubContextClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GamesPortalHubContextClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GamesPortalHubContextClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GamesPortalHubContextClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GameSynchronizationFinished(GamesPortal.Client.Models.GamesPortalHubContracts.GameSynchronizationFinishedData data) {
            base.Channel.GameSynchronizationFinished(data);
        }
        
        public System.Threading.Tasks.Task GameSynchronizationFinishedAsync(GamesPortal.Client.Models.GamesPortalHubContracts.GameSynchronizationFinishedData data) {
            return base.Channel.GameSynchronizationFinishedAsync(data);
        }
        
        public void FullGamesSynchronizationFinished(GamesPortal.Client.Models.GamesPortalHubContracts.FullGamesSynchronizationFinishedData data) {
            base.Channel.FullGamesSynchronizationFinished(data);
        }
        
        public System.Threading.Tasks.Task FullGamesSynchronizationFinishedAsync(GamesPortal.Client.Models.GamesPortalHubContracts.FullGamesSynchronizationFinishedData data) {
            return base.Channel.FullGamesSynchronizationFinishedAsync(data);
        }
    }
}
