//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InvestTracker.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuyTransaction
    {
        public System.Guid Transaction_ID { get; set; }
        public System.Guid Fund_ID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Price { get; set; }
        public decimal NumberOfUnits { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Fund Fund { get; set; }
    }
}
