//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GamesPortal.Service.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.20.49.75;Initial Catalog=_dicts;Persist Security Info=True;User ID" +
            "=RealCasinoUser;Password=RealCasinoUser")]
        public string _dictsConnectionString {
            get {
                return ((string)(this["_dictsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.20.40.158;Initial Catalog=GGPVersioningDB;Integrated Security=True" +
            "")]
        public string GGPVersioningDBConnectionString {
            get {
                return ((string)(this["GGPVersioningDBConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=ClientApprovalSystem;Integrated Security=Tr" +
            "ue")]
        public string ClientApprovalSystemConnectionString {
            get {
                return ((string)(this["ClientApprovalSystemConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=GamesPortalDEV;Integrated Security=True")]
        public string GamesPortalDEVConnectionString {
            get {
                return ((string)(this["GamesPortalDEVConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.20.49.176;Initial Catalog=_dicts;Persist Security Info=True;User I" +
            "D=RealCasinoUser;Password=RealCasinoUser")]
        public string _dictsConnectionString1 {
            get {
                return ((string)(this["_dictsConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.20.40.228;Initial Catalog=DB_SDM_Admin;Persist Security Info=True;" +
            "User ID=rldev;Password=developme")]
        public string DB_SDM_AdminConnectionString {
            get {
                return ((string)(this["DB_SDM_AdminConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=REAL-APR-DEV;Initial Catalog=JackPotInfo;Persist Security Info=True;U" +
            "ser ID=rldev;Password=developme")]
        public string JackPotInfoConnectionString {
            get {
                return ((string)(this["JackPotInfoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=REAL-APR-DEV;Initial Catalog=DB_SDM_Admin;Persist Security Info=True;" +
            "User ID=rldev;Password=developme")]
        public string DB_SDM_AdminConnectionString1 {
            get {
                return ((string)(this["DB_SDM_AdminConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=GamesPortalDev2;Integrated Security=True")]
        public string GamesPortalDev2ConnectionString {
            get {
                return ((string)(this["GamesPortalDev2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=10.20.49.176;Initial Catalog=DB_SDM;Persist Security Info=True;User I" +
            "D=rlqa;Password=testmenow")]
        public string DB_SDMConnectionString {
            get {
                return ((string)(this["DB_SDMConnectionString"]));
            }
        }
    }
}
